### ISSUE TITLE
Error: Couldn't open file '-list': No such file or directory.

### ISSUE THREAD

**Issue by buzzbo** [dsanson/termpdf#1]
I get this error when I try to run the command

```
$ termpdf bash.pdf
Error: Couldn't open file '-list': No such file or directory.
```

The error appears very briefly, then it opens a blank page; ^c gets me back to the prompt.

[Here is the pdf](https://www.dropbox.com/s/xf26tdg1k02he69/bash.pdf?dl=0) I used (dropbox link).

Edit: does this only work on a _Mac_?

**Comment by dsanson** [comment]
Sorry, yes, this is Mac only, because it depends on iTerm2. It shouldn't be hard to add support for X11 and framebuffer, using w3m's w3mimgdisplay utility (you can see [how ranger does this here](https://github.com/hut/ranger/blob/master/ranger/ext/img_display.py).  But my version of w3m doesn't include w3mimgdisplay, so I don't have any easy way to test that.

**Comment by buzzbo** [comment]
Ah OK. If I was more devvy I would probably look into that, but I'll just watch. Thanks.

**Comment by dsanson** [comment]
I just added support for X11 using w3m. Try it out.
