### ISSUE TITLE
Blank terminal when opening pdf file in z-shell

### ISSUE THREAD

**Issue by nafizh** [dsanson/termpdf#11]
My iTerm runs z-shell instead of bash. I don't know if that is the reason but when I try to open a pdf, the terminal just gives a blank page.

<img width="1438" alt="screen shot 2016-04-16 at 8 38 47 pm" src="https://cloud.githubusercontent.com/assets/9099617/14584578/4681b48e-0413-11e6-99b3-1c602e4868c4.png">

Interestingly, it does show the page number of the book in the bottom right.

**Comment by dsanson** [comment]
I run in zsh too, so that shouldn't be the issue.
-    Have you tried refreshing the page, by hitting 'r'?
-    Does this just happen with some PDFs or all? 
-    Some but not all PDFs have a transparent background. Since your background is black, it is possible that it is displaying the black text on the black background. The solution is to find a tool that sets the PDF background to white without unreasonable overhead. The workaround is to use a light colored background in iTerm. See issue #10.
-    For me, some PDFs don't properly display the first page (especially if it is a book cover). I haven't figured out why. Have you tried viewing other pages? e.g., what happens if you hit the space bar a few times to move to page 2 or 3 or 4?
-    For me, a small number of PDFs simply don't display properly, for reasons I haven't figured out.

**Comment by ghost** [comment]
@dsanson I ran into this same issue and the background color was indeed the problem. @nafizh?
