### ISSUE TITLE
Low quality output

### ISSUE THREAD

**Issue by rien333** [dsanson/termpdf#14]
All the pdfs that I display with `termpdf` look way worse than if I for example open them in Preview.app . I would say that they look as if the pages were actually low resolution images and that they have a pretty grainy feel to them (this is especially true for text) Is this an inherent limitation or a bug on my side?

**Comment by dsanson** [comment]
Good question. I have also noticed that the image quality is often worse than it would be in Preview. The script uses Poppler's `pdfseparate` to extract individual pages as PDFs, and then feeds those single-page pdfs directly to iTerm. I don't think `pdfseparate` does anything to reduce the quality of the PDFs. So I suspect it has something to do with the way iTerm handles PDFs?

A previous iteration of the script instead extracted each page as a PNG image. An obvious test would be to see if you can get better image quality from a given PDF by using some other tool to extract a high resolution PNG image, and then viewing that image using termpdf.

**Comment by dsanson** [comment]
Commit  aaae2882715a93b2f88f83acbbf2056560800878 should address this issue: to make it work with kitty, I tweaked the script so that it once again converts each page to a png, rather than leaving the conversion to iterm. So now we can control the quality of the image by setting the resolution when we convert it: try tweaking the `-r 200` on line 491 of the script. On my laptop, high resolutions slow things down significantly, though.

**Comment by rien333** [comment]
Thank you for fixing this! 

Kitty support is quite buggy for me btw. Sometimes I have image output, but only on smaller terminal-windows

**Comment by dsanson** [comment]
Yeah, I should make it clear that Kitty support is experimental at this point.

**Comment by dsanson** [comment]
See https://github.com/kovidgoyal/kitty/issues/276

One temporary workaround: if no image is displayed in kitty, try changing the font size.

**Comment by dsanson** [comment]
Should now be fixed upstream.
